"""language update

Revision ID: 099f47962713
Revises: 01db00821956
Create Date: 2025-02-02 20:58:22.573501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '099f47962713'
down_revision = '01db00821956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.String(length=255), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.BINARY(length=16), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.BINARY(length=16), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
