"""user mixin updated

Revision ID: 29b91fdfb6c1
Revises: 668da2d1f66f
Create Date: 2025-01-28 18:40:10.949444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29b91fdfb6c1'
down_revision = '668da2d1f66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_template', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_template', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
