"""language name update

Revision ID: 2c468f1c1098
Revises: 099f47962713
Create Date: 2025-02-02 21:03:55.918824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c468f1c1098'
down_revision = '099f47962713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('flag', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('translation',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('context', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BINARY(length=16), nullable=True),
    sa.Column('updated_by', sa.BINARY(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('translation_value',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('translation_id', sa.BINARY(length=16), nullable=False),
    sa.Column('language_id', sa.BINARY(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BINARY(length=16), nullable=True),
    sa.Column('updated_by', sa.BINARY(length=16), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['translation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index('code')

    op.drop_table('languages')
    op.drop_table('translation_values')
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_index('key')

    op.drop_table('translations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('context', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', sa.BINARY(length=16), nullable=True),
    sa.Column('updated_by', sa.BINARY(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.create_index('key', ['key'], unique=True)

    op.create_table('translation_values',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('translation_id', sa.BINARY(length=16), nullable=False),
    sa.Column('language_id', sa.BINARY(length=16), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', sa.BINARY(length=16), nullable=True),
    sa.Column('updated_by', sa.BINARY(length=16), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name='translation_values_ibfk_1'),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.id'], name='translation_values_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('languages',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('flag', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index('code', ['code'], unique=True)

    op.drop_table('translation_value')
    op.drop_table('translation')
    op.drop_table('language')
    # ### end Alembic commands ###
