"""Add password, role, and auth_provider columns to User model

Revision ID: 2df724ea1027
Revises: 
Create Date: 2024-12-10 19:21:07.869359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2df724ea1027'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('users')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('role')
        batch_op.drop_column('password')

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fullname', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.ENUM('enable', 'disable'), server_default=sa.text("'enable'"), nullable=True),
    sa.Column('role', mysql.ENUM('admin', 'user'), server_default=sa.text("'user'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
