"""add rtl to language

Revision ID: 4ded49452d6e
Revises: b163b9efdd07
Create Date: 2025-02-17 18:27:20.421564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ded49452d6e'
down_revision = 'b163b9efdd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
