"""add language default

Revision ID: 695a94971680
Revises: 2c468f1c1098
Create Date: 2025-02-07 22:36:00.819545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695a94971680'
down_revision = '2c468f1c1098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('default')

    # ### end Alembic commands ###
