"""change tranlation value to Text

Revision ID: 6e0c4adb43ab
Revises: 8f57cb333e31
Create Date: 2025-02-09 14:57:46.369741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e0c4adb43ab'
down_revision = '8f57cb333e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
