"""add rtl to language

Revision ID: 8f51d9e686ab
Revises: 4ded49452d6e
Create Date: 2025-02-17 18:31:19.853775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f51d9e686ab'
down_revision = '4ded49452d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rtl', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('rtl')

    # ### end Alembic commands ###
