"""add source type filed to translation

Revision ID: 8f57cb333e31
Revises: a7094db51234
Create Date: 2025-02-09 13:36:18.079004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f57cb333e31'
down_revision = 'a7094db51234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
