"""Add language_id to users

Revision ID: a7094db51234
Revises: 695a94971680
Create Date: 2025-02-08 23:13:27.131965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7094db51234'
down_revision = '695a94971680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_id', sa.BINARY(length=16), nullable=True))
        batch_op.create_foreign_key(None, 'language', ['language_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('language_id')

    # ### end Alembic commands ###
