"""Change translation context size

Revision ID: b163b9efdd07
Revises: 6e0c4adb43ab
Create Date: 2025-02-11 14:17:09.327207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b163b9efdd07'
down_revision = '6e0c4adb43ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.alter_column('context',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation', schema=None) as batch_op:
        batch_op.alter_column('context',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
