"""add description to cache server

Revision ID: f3fa1c38dcd5
Revises: 6dcc8fe56794
Create Date: 2025-02-24 09:25:58.923581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fa1c38dcd5'
down_revision = '6dcc8fe56794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cache_server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cache_server', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
